name: Visual Studio Extension for Emscripten

on:
  [ push, pull_request ]

jobs:

  build:

    runs-on: windows-2016  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Emscripten.sln
      MSBuild_Path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\bin"


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore the package
      run: nuget restore $env:Solution_Name
      
    - name: Build the application
      run: |
        Set-Item Env:Path "$env:MSBuild_Path;$env:Path"
        msbuild $env:Solution_Name /p:Configuration=Release

    - name: Save Bundles (for VS2017)
      uses: actions/upload-artifact@v2
      with:
        name: VS2017-Emscripten
        path: .\Emscripten.ProjectType\bin\Release\*.vsix
    
    - name: Save Bundles (for VS2019)
      uses: actions/upload-artifact@v2
      with:
        name: VS2019-Emscripten
        path: .\Emscripten.ProjectPackage.vs2019\bin\Release\*.vsix    
  
